#!c:\Users\Almazt\OneDrive - Ethiopian Airlines\Desktop\10 Academy\AlphaCare Insurance Soln\jupyter_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
